### PR TITLE
Replace ColorLogger with Rich library

### PR DESCRIPTION
**Pull request by MarkZH**
The Rich library provides an easier-to-use logging colorizer. Color markup is now removed from the logs when written to a file with -l.

### CODE REVIEW

**Comment by MarkZH** [comment]
Some samples of the new output:

Basic console logging:
info logging

Verbose console logging (-v):
debug logging

Basic logging to a file:
```
2022-06-30 22:56:38,024: 
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.2.0
    .  //__\
    .  )___(   Play on Lichess with a bot
    
2022-06-30 22:56:50,665 __main__ INFO Welcome Genetic_Chess_Bot!
2022-06-30 22:56:50,665 __main__ INFO You're now connected to https://lichess.org/ and awaiting challenges.
2022-06-30 22:58:54,228 __main__ INFO Challenging a random bot
2022-06-30 22:59:00,351 matchmaking INFO Will challenge Opulent_Ophelia for a standard game.
2022-06-30 22:59:01,367 matchmaking INFO Challenge id is MXlAWeuW.
2022-06-30 22:59:01,776 __main__ INFO Accept Bullet rated challenge from BOT Genetic_Chess_Bot(1654)
2022-06-30 22:59:02,175 __main__ INFO Skip missing Bullet rated challenge from BOT Genetic_Chess_Bot(1654)
2022-06-30 22:59:02,196 __main__ INFO --- Process Used. Total Queued: 0. Total Used: 1
2022-06-30 22:59:07,190 __mp_main__ INFO +++ https://lichess.org/MXlAWeuW/white Bullet vs BOT Opulent_Ophelia(2509)
2022-06-30 22:59:20,290 __mp_main__ INFO 
2022-06-30 22:59:20,291 __mp_main__ INFO move: 1
2022-06-30 22:59:20,293 __mp_main__ INFO Searching for time 10000
2022-06-30 22:59:24,766 engine_wrapper INFO depth: 6
2022-06-30 22:59:24,766 engine_wrapper INFO nps: 291111
2022-06-30 22:59:24,767 engine_wrapper INFO nodes: 1300524
2022-06-30 22:59:24,767 engine_wrapper INFO score: PovScore(Cp(0), WHITE)
2022-06-30 22:59:24,767 engine_wrapper INFO ponderpv: 1. b3 b6 2. Bb2 Nf6 3. a4 Ne4
2022-06-30 22:59:25,178 conversation INFO *** https://lichess.org/MXlAWeuW/white [player] Genetic_Chess_Bot: b"Hi! I'm Genetic_Chess_Bot. Good luck! Type !help for a list of commands I can respond to."
2022-06-30 22:59:25,684 conversation INFO *** https://lichess.org/MXlAWeuW/white [player] Opulent_Ophelia: b"Hi! I'm Opulent_Ophelia. Good luck! Type !help for a list of commands I can respond to."
2022-06-30 22:59:25,685 __mp_main__ INFO 
2022-06-30 22:59:25,685 __mp_main__ INFO move: 2
2022-06-30 22:59:25,686 __mp_main__ INFO Searching for wtime 119700 btime 120000
```

Verbose logging to a file: (-v):
```
2022-06-30 22:49:57,011: 
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 1.2.0
    .  //__\
    .  )___(   Play on Lichess with a bot
    
2022-06-30 22:49:57,023 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): lichess.org:443
2022-06-30 22:50:00,311 backoff DEBUG Backing off api_get(...) for 0.1s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='lichess.org', port=443): Read timed out. (read timeout=2))
2022-06-30 22:50:00,420 urllib3.connectionpool DEBUG Starting new HTTPS connection (2): lichess.org:443
2022-06-30 22:50:02,658 urllib3.connectionpool DEBUG https://lichess.org:443 "GET /api/account HTTP/1.1" 200 None
2022-06-30 22:50:02,659 __main__ INFO Welcome Genetic_Chess_Bot!
2022-06-30 22:50:02,659 __main__ INFO You're now connected to https://lichess.org/ and awaiting challenges.
2022-06-30 22:50:03,588 urllib3.connectionpool DEBUG https://lichess.org:443 "GET /api/account/playing HTTP/1.1" 200 17
2022-06-30 22:52:08,661 __main__ INFO Challenging a random bot
2022-06-30 22:52:08,666 urllib3.connectionpool DEBUG Resetting dropped connection: lichess.org
2022-06-30 22:52:10,921 urllib3.connectionpool DEBUG https://lichess.org:443 "GET /api/bot/online HTTP/1.1" 200 None
2022-06-30 22:52:14,140 matchmaking INFO Will challenge ChessChildren for a standard game.
2022-06-30 22:52:14,542 urllib3.connectionpool DEBUG https://lichess.org:443 "POST /api/challenge/ChessChildren HTTP/1.1" 200 None
2022-06-30 22:52:14,544 matchmaking INFO Challenge id is Rk6TwD8p.
2022-06-30 22:52:14,563 __main__ DEBUG Event: {'type': 'challenge', 'challenge': {'id': 'Rk6TwD8p', 'url': 'https://lichess.org/Rk6TwD8p', 'status': 'created', 'challenger': {'id': 'genetic_chess_bot', 'name': 'Genetic_Chess_Bot', 'title': 'BOT', 'rating': 1668, 'online': True}, 'destUser': {'id': 'chesschildren', 'name': 'ChessChildren', 'title': 'BOT', 'rating': 1781, 'online': True}, 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'rated': True, 'speed': 'bullet', 'timeControl': {'type': 'clock', 'limit': 120, 'increment': 0, 'show': '2+0'}, 'color': 'random', 'finalColor': 'white', 'perf': {'icon': '\ue047', 'name': 'Bullet'}}, 'compat': {'bot': True, 'board': False}}
2022-06-30 22:52:14,567 __main__ INFO Accept Bullet rated challenge from BOT Genetic_Chess_Bot(1668)
2022-06-30 22:52:14,973 urllib3.connectionpool DEBUG https://lichess.org:443 "POST /api/challenge/Rk6TwD8p/accept HTTP/1.1" 404 None
2022-06-30 22:52:14,975 backoff DEBUG Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/api/challenge/Rk6TwD8p/accept)
2022-06-30 22:52:14,976 __main__ INFO Skip missing Bullet rated challenge from BOT Genetic_Chess_Bot(1668)
2022-06-30 22:52:14,978 __main__ DEBUG Event: {'type': 'gameStart', 'game': {'fullId': 'Rk6TwD8pvkQV', 'gameId': 'Rk6TwD8p', 'fen': 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', 'color': 'white', 'lastMove': '', 'source': 'friend', 'variant': {'key': 'standard', 'name': 'Standard'}, 'speed': 'bullet', 'perf': 'bullet', 'rated': True, 'hasMoved': False, 'opponent': {'id': 'chesschildren', 'username': 'BOT ChessChildren', 'rating': 1781}, 'isMyTurn': True, 'secondsLeft': 120, 'compat': {'bot': True, 'board': False}, 'id': 'Rk6TwD8p'}}
2022-06-30 22:52:14,978 __main__ INFO --- Process Used. Total Queued: 0. Total Used: 1
2022-06-30 22:52:15,001 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): lichess.org:443
2022-06-30 22:52:20,083 urllib3.connectionpool DEBUG https://lichess.org:443 "GET /api/bot/game/stream/Rk6TwD8p HTTP/1.1" 200 None
2022-06-30 22:52:20,087 __mp_main__ DEBUG Initial state: {'id': 'Rk6TwD8p', 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'clock': {'initial': 120000, 'increment': 0}, 'speed': 'bullet', 'perf': {'name': 'Bullet'}, 'rated': True, 'createdAt': 1656600734671, 'white': {'id': 'genetic_chess_bot', 'name': 'Genetic_Chess_Bot', 'title': 'BOT', 'rating': 1668}, 'black': {'id': 'chesschildren', 'name': 'ChessChildren', 'title': 'BOT', 'rating': 1781}, 'initialFen': 'startpos', 'type': 'gameFull', 'state': {'type': 'gameState', 'moves': '', 'wtime': 120000, 'btime': 120000, 'winc': 0, 'binc': 0, 'status': 'started'}}
2022-06-30 22:52:20,088 engine_wrapper DEBUG Starting engine: C:\users\mark harrison\documents\github\genetic_chess\x64\release\Genetic_Chess.exe --genetic=genome_example.txt --game-file=lichess-games.pgn
2022-06-30 22:52:20,092 asyncio DEBUG Using proactor: IocpProactor
2022-06-30 22:52:20,204 chess.engine DEBUG <UciProtocol (pid=14692)>: Connection made
2022-06-30 22:52:20,205 chess.engine DEBUG <UciProtocol (pid=14692)>: << uci
2022-06-30 22:52:20,234 chess.engine DEBUG <UciProtocol (pid=14692)>: >> id name Genetic Chess #704622
2022-06-30 22:52:20,235 chess.engine DEBUG <UciProtocol (pid=14692)>: >> id author Mark Harrison
2022-06-30 22:52:20,235 chess.engine DEBUG <UciProtocol (pid=14692)>: >> option name UCI_Opponent type string
2022-06-30 22:52:20,235 chess.engine DEBUG <UciProtocol (pid=14692)>: >> uciok
2022-06-30 22:52:20,236 chess.engine DEBUG <UciProtocol (pid=14692)>: << setoption name UCI_Opponent value BOT 1781 computer ChessChildren
2022-06-30 22:52:20,237 __mp_main__ INFO +++ https://lichess.org/Rk6TwD8p/white Bullet vs BOT ChessChildren(1781)
2022-06-30 22:52:20,237 __mp_main__ DEBUG Game state: {'type': 'gameState', 'moves': '', 'wtime': 120000, 'btime': 120000, 'winc': 0, 'binc': 0, 'status': 'started'}
2022-06-30 22:52:20,239 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): lichess.org:443
2022-06-30 22:52:22,445 urllib3.connectionpool DEBUG https://lichess.org:443 "POST /api/bot/game/Rk6TwD8p/chat HTTP/1.1" 200 11
2022-06-30 22:52:22,448 __mp_main__ INFO 
2022-06-30 22:52:22,449 __mp_main__ INFO move: 1
2022-06-30 22:52:22,450 __mp_main__ INFO Searching for time 10000
2022-06-30 22:52:22,452 chess.engine DEBUG <UciProtocol (pid=14692)>: << ucinewgame
2022-06-30 22:52:22,453 chess.engine DEBUG <UciProtocol (pid=14692)>: << isready
2022-06-30 22:52:22,455 chess.engine DEBUG <UciProtocol (pid=14692)>: >> readyok
2022-06-30 22:52:22,457 chess.engine DEBUG <UciProtocol (pid=14692)>: << position startpos
2022-06-30 22:52:22,458 chess.engine DEBUG <UciProtocol (pid=14692)>: << go movetime 10000
2022-06-30 22:52:23,462 chess.engine DEBUG <UciProtocol (pid=14692)>: >> info depth 6 time 1002 nodes 281095 nps 280519 pv b1a3 g8f6 a3b1 a7a6 a2a3 b7b6 score cp -14 currmove b1a3
2022-06-30 22:52:24,462 chess.engine DEBUG <UciProtocol (pid=14692)>: >> info depth 7 time 2002 nodes 562613 nps 281009 pv f2f4 a7a6 g1h3 a6a5 h3f2 a5a4 a2a3 score cp 2 currmove f2f4
2022-06-30 22:52:25,462 chess.engine DEBUG <UciProtocol (pid=14692)>: >> info depth 6 time 3002 nodes 853442 nps 284260 pv g2g3 b8c6 f1g2 c6b8 a2a4 g8f6 score cp 2 currmove g2g3
2022-06-30 22:52:26,466 chess.engine DEBUG <UciProtocol (pid=14692)>: >> info depth 7 time 4005 nodes 1145368 nps 285972 pv h2h3 b7b6 f2f4 a7a6 e2e3 a6a5 d1f3 score cp 0 currmove h2h3
2022-06-30 22:52:27,445 chess.engine DEBUG <UciProtocol (pid=14692)>: >> info depth 13 time 4984 nodes 1435606 nps 288004 pv h2h3 b7b6 b2b3 c8b7 g1f3 h7h5 h1h2 h8h6 h2h1 h6h8 h1g1 h8h6 g1h1 score cp 0 currmove h2h3
2022-06-30 22:52:27,446 chess.engine DEBUG <UciProtocol (pid=14692)>: >> bestmove h2h3
2022-06-30 22:52:27,446 engine_wrapper INFO depth: 13
2022-06-30 22:52:27,447 engine_wrapper INFO nps: 288004
2022-06-30 22:52:27,447 engine_wrapper INFO nodes: 1435606
2022-06-30 22:52:27,447 engine_wrapper INFO score: PovScore(Cp(0), WHITE)
2022-06-30 22:52:27,448 engine_wrapper INFO ponderpv: 1. h3 b6 2. b3 Bb7 3. Nf3 h5 4. Rh2 Rh6 5. Rh1 Rh8 6. Rg1 Rh6 7. Rh1
2022-06-30 22:52:27,853 urllib3.connectionpool DEBUG https://lichess.org:443 "POST /api/bot/game/Rk6TwD8p/move/h2h3?offeringDraw=false HTTP/1.1" 200 11
2022-06-30 22:52:27,853 __mp_main__ DEBUG Game state: {'type': 'chatLine', 'room': 'player', 'username': 'Genetic_Chess_Bot', 'text': "Hi! I'm Genetic_Chess_Bot. Good luck! Type !help for a list of commands I can respond to."}
```

**Comment by MarkZH** [comment]
This should be tested on Linux and Mac, neither of which I have access to at the moment.

**Comment by AttackingOrDefending** [comment]
I tested it on Windows and Linux and it works.
Linux terminal using -v:
linux

**Review by AttackingOrDefending — APPROVED** [review]

**Comment by MarkZH** [comment]
I'm done with this PR. Go ahead and merge if you approve the new changes.

**Pull request merged**
