### PR TITLE
Record games played by bot to local files

### LINKED ISSUE #175: Write bot move info (eval, pv, depth) into a pgn
The simplest way to do this would probably be to always write to some local pgn file, e.g. with the pgn name being the game id. (that way even through dis- and reconnecting it should (?) still write to the same file)
Then for now the bot maintainer can upload the pgn manually into some study or similar although later it might also be interesting to add an "!analysis" command that spectators or the opponent can use to have the bot automatically upload the pgn into a study after the game, provided there is a lichess api endpoint for that.

As for what should be written in there, I think the relevant infos are 1. pv 2. eval 3. depth.

### PR DESCRIPTION
**Pull request by MarkZH**
Add a configuration to have lichess-bot record a bot's games to a folder on the user's computer. The games are written in PGN format and include the bot's evaluation of the move--including the score and principle variation.

Depending on what characters are allowed in lichess account names, some more characters may need to be filtered out of file names. Right now, only question marks are removed (as from uncertain chess ratings).

Also, this may be too paranoid:
```python
try:
    print_pgn_game_record(config, game, board, engine, start_datetime)
except Exception:
    pass
```

Closes #175

### CODE REVIEW

**Comment by AttackingOrDefending** [comment]
Can you change single quotes to double quotes in test_bot.py, so it is like the rest of the code?

**Comment by MarkZH** [comment]
Or, I could just get rid of all the invalid characters myself. The game ID will keep separate games in separate files.

Also, one feature I forgot to mention: if a game on lichess gets interruptedd (say, by network trouble or disconnecting during a correspondence game), the partial game will be written to the file. When the game is resumed, the same file will be completed with the rest of the game. However, stopping lichess-bot with Ctrl-C will stop any game information from being written, so if a game is in progress, Ctrl-C will lose the bot evaluation information, even if the game is completed later.

**Comment by AttackingOrDefending** [comment]
`try: except:` for files can probably be replaced with `os.path.exists(path)`.
To add the engine score I think you can use https://python-chess.readthedocs.io/en/latest/pgn.html#chess.pgn.GameNode.set_eval.

**Comment by MarkZH** [comment]
Hold off on merging for a bit. With these new methods, the score written to the PGN is always from white's perspective, even if the bot is playing black. I reported this as [an issue at the python-chess repository](https://github.com/niklasf/python-chess/issues/856) asking about this.

**Comment by MarkZH** [comment]
OK. This is ready for review.

**Review by AttackingOrDefending — APPROVED** [review]

**Pull request merged**
