### PR TITLE
Suppress API error messages by default / Keep connection after game timeout

### LINKED ISSUE #411: Games end with `400 Client Error` for UCI Bots
At the end of each game an error occurs (in relation Draw Offering) `Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/gGXh05ih/move/e4e5?offeringDraw=false)` as seen below when `python3 lichess-bot.py -u` is used to start the bot:

```
move: 49
Searching for wtime 0 btime 1120
depth: 3
nps: 77000
nodes: 77
score: PovScore(Cp(+1226), WHITE)
Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/gGXh05ih/move/e4e5?offeringDraw=false)
--- https://lichess.org/gGXh05ih/white Game over
+++ Process Free. Total Queued: 0. Total Used: 0
```

These are the logs I get when I run `python3 lichess-bot.py -v`:
```
<UciProtocol (pid=72)>: >> info depth 14 seldepth 26 multipv 1 score cp 1553 nodes 394641 nps 1157304 tbhits 0 time 341 pv g3f4 g1f1 f2f3 f1h1 h4h5 g7f8 h5h6 f8e7 g4g5 h1d1 f4g4 e7f7 g5g6 f7f8 g4f5 f8e7 g6g7 e7f7
https://lichess.org:443 "POST /api/bot/game/0uojtTZ4/move/a3a6?offeringDraw=false HTTP/1.1" 400 43
Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/0uojtTZ4/move/a3a6?offeringDraw=false)
https://lichess.org:443 "GET /api/account/playing HTTP/1.1" 200 17
<UciProtocol (pid=72)>: << stop
<UciProtocol (pid=72)>: << quit
<UciProtocol (pid=72)>: >> info depth 15 seldepth 24 multipv 1 score cp 1530 nodes 644271 nps 1158760 tbhits 0 time 556 pv g3f4
<UciProtocol (pid=72)>: >> bestmove g3f4 ponder g1b1
<UciProtocol (pid=72)>: >> info depth 14 seldepth 19 multipv 1 score cp 1211 nodes 130763 nps 983180 tbhits 0 time 133 pv a3a6 d4d8 g4g5 d8d5 g3g4 d5d8 h4h5 g7f8 a6a7 f8g8 f2f4 g8f8 h5h6 f8g8 g5g6 d8c8
<UciProtocol (pid=72)>: >> info depth 15 seldepth 20 multipv 1 score cp 1179 nodes 261951 nps 1003643 tbhits 0 time 261 pv a3a6 d4d3 f2f3 d3d1 g4g5 d1g1 g3f4 g1h1 f4g4 h1g1 g4f5 g1f1 f3f4 f1h1 h4h5 h1h5 a6h6 h5h6 g5h6 g7g8 f5f6
<UciProtocol (pid=72)>: Process exited
<UciProtocol (pid=72)>: Connection lost (exit code: 0, error: None)
--- https://lichess.org/0uojtTZ4/white Game over
+++ Process Free. Total Queued: 0. Total Used: 0
```
I'm not sure if this error occurs even with XBoard bots, but it does ocuurs with Bots running under the UCI protocol. Also this error doesn't effect the bot. Once a new game starts it plays the game, but at the end of each game this error occurs.

### PR DESCRIPTION
**Pull request by MarkZH**
If a bot runs out of time, this change will make sure that the last message
from lichess is received. Prior to this change, the user would only see
an api_post() error and the game would end.

This should fix #411.

### CODE REVIEW

**Comment by AttackingOrDefending** [comment]
This PR makes the `tell_user_game_result` work if the bot loses on time but I still get the error `2022-01-30 00:00:00,000: Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/Ss4AAYMl/move/b4b5?offeringDraw=false)`. Is this the expected behavior?

**Comment by MarkZH** [comment]
@AttackingOrDefending @TheYoBots 
It is expected, but I'm trying to figure out if it's good behavior. The latest commit changes the logging level of the `backoff` decorators (lines 39 and 51 in lichess.py) when they give up to DEBUG so that they would only appear when lichess-bot is run with `-v`. I'll add a new commit with this behavior. Let me know if it's a good idea to hide these communication errors by default.

**Comment by MarkZH** [comment]
Side note: I'm not sure if changing the logging level on every call to `api_get()` and `api_post()` is the correct way to go about this, but it's the only thing that works. I was using a Windows computer to develop this, so my roundabout solution might be similar to issue #290 and PR #294.

**Comment by AttackingOrDefending** [comment]
I don't think it is a problem to hide these communication errors by default as long as they can be accessed with `-v`. Is this ready to be merged?

**Comment by MarkZH** [comment]
Yep. Ready for merging.

**Pull request merged**
