### PR TITLE
Syzygy tablebases

### PR DESCRIPTION
**Pull request by OIVAS7572**
i got this error :
"chess.engine.EngineError: engine does not support option egtpath (available options: Debug Log File, Contempt, Analysis Contempt, Threads, Hash, Clear Hash, Ponder, MultiPV, Skill Level, Move Overhead, Slow Mover, nodestime, UCI_Chess960, UCI_AnalyseMode, UCI_LimitStrength, UCI_Elo, UCI_ShowWDL, SyzygyPath, SyzygyProbeDepth, Syzygy50MoveRule, SyzygyProbeLimit, Use NNUE, EvalFile
"
Check my request
If there is no problem add this

### CODE REVIEW

**Comment by TheYoBots** [comment]
I suggest you place “SyzygyPath” after line 28 as it is a uci option. Also there are very few uci engines that support syzygy tablebases and lichess-bot is more of a general bot client made to support various types of engines. So I’m not to sure this would help for many engines. Also renaming this PR to “Syzygy tablebases” is more suited because that’s what this does. Not really a correction.

**Comment by OIVAS7572** [comment]
egtb is common for uci and xboard

**Comment by OIVAS7572** [comment]
only remove hash if their engine support syzygy tb.
33 line also come under uci option.

**Comment by TheYoBots** [comment]
1. egtpath is only applicable for xboard in lichess-bot. It is not for both uci and xboard. If you would like to add endgame tablebases then it will come right under uci_options.
2. Not all engines use syzygy tablebases, some support only gaviota, and some support none. Very few support syzygy in particular. So lichess-bot being something more general to support various uci and xboard engines can’t specifically mention SyzygyPath as that can result in various engines not working.

**Comment by OIVAS7572** [comment]
I change that to 28th line

**Comment by TheYoBots** [comment]
1. egtb support for xboard has been completed removed, so please add that.
2. Again syzygy tablebases are not extensively used by all uci engines, and that’s why it wasn’t added. Though the strongest available engine (Stockfish) supports it.

**Comment by MarkZH** [comment]
The options listed in `config.yml.default` are there as examples. There's nothing stopping users from adding their own custom options to their `config.yml`. Your engine has a configuration for `SyzygyPath`, so you can add it to your own `config.yml` in the `uci_options` section. There's no need for a pull request since your `config.yml` should be specific to your engine.

**Comment by OIVAS7572** [comment]
@MarkZH  
It is not the problem of my engine.
In the new version of python-chess library.
There is no option for :
egtpath
gaviota
nalimov
scorpio
syzygy
The available options are in this error comment:
https://github.com/ShailChoksi/lichess-bot/pull/286#issue-592283643

**Comment by TheYoBots** [comment]
@OIVAS7572 Those options you are mentioning were always for only xboard engines, not for uci engines.

**Comment by OIVAS7572** [comment]
Where I want to keep that

**Comment by OIVAS7572** [comment]
I understand the problem. I am closing

**Pull request closed without merging**
