### PR TITLE
Improvements for PGN writing

### PR DESCRIPTION
**Pull request by MarkZH**
1. Download PGN record from lichess.org. The lichess record includes more detailed header info (like opening identification) and extra move info like time remaining on clock.
2. Simplify `print_pgn_game_record()` code. The resulting function code is much simpler, especially the alignment of new move comments from engines after disconnecting from a game.
3. File names only include the players' names, not their titles and ratings.

### CODE REVIEW

**Comment by MarkZH** [comment]
@TheYoBots @AttackingOrDefending 

These changes could use some testing. I believe they work both for games that are finished in one session and games that are interrupted by disconnections (whether through network errors or correspondence game inactivity).

**Comment by MarkZH** [comment]
I've added the reason for a game ending ("White resigns," "Black forfeits on time," etc.) as a comment to the last move.

I can copy the Opening and ECO information into a comment on the first move. Should I implement that? Or is the opening information in the headers sufficient?

**Comment by AttackingOrDefending** [comment]
Lichess adds a comment with the opening at the move this opening was reached. In the game above it was after d4, d5, c4 and e6.
1. d4 { D30 Queen's Gambit Declined } isn't correct, because d4 alone is only queen's pawn game. I think that it would be best to put the comment after the correct move (by leaving the comment from lichess) but if this is not possible, I would prefer not having it at all.

**Comment by MarkZH** [comment]
All lichess annotations should be written to the file now.

**Comment by MarkZH** [comment]
Now this is ready for the next review.

**Comment by AttackingOrDefending** [comment]
When there is a lichess comment, a new line is added before it.
For example:

> [Event "Casual Bullet game"]
[Site "https://lichess.org/mEhSUmjf"]
[Date "2022.03.18"]
[Round "?"]
[White "CenturyGaming"]
[Black "AttackingOrDefending"]
[Result "0-1"]
[Annotator "lichess.org"]
[BlackElo "2378"]
[BlackTitle "BOT"]
[ECO "C44"]
[Opening "Ponziani Opening: Neumann Gambit"]
[Termination "Normal"]
[TimeControl "60+2"]
[UTCDate "2022.03.18"]
[UTCTime "18:34:53"]
[Variant "Standard"]
[WhiteElo "2074"]
> 
> 1. e4 { [%clk 0:01:00] } 1... e5 { [%clk 0:01:00] } 2. Nf3 { [%clk 0:01:00] }
2... Nc6 { [%clk 0:01:01] } 3. Bc4 { [%clk 0:00:59] } 3... Nf6
{ [%clk 0:01:02] } 4. c3
{ [%clk 0:00:58] (**here**)
C44 Ponziani Opening: Neumann Gambit } 4... Nxe4
{ [%clk 0:01:04] } 5. d3 { [%clk 0:00:59] } 5... Nf6 { [%clk 0:01:05] } 6. O-O
{ [%clk 0:00:59] } 6... Be7 { [%clk 0:01:07] (**and here**)
White resigns. } 0-1

**Comment by MarkZH** [comment]
Spurious newlines should be gone now.

**Comment by AttackingOrDefending** [comment]
While I was testing it, in one game it got an error while writing the PGN file and left it unfinished. It seems that this was caused because the bot played an engine move, then an opening book move and then went back to engine moves (moves 11-13).
Game PGN:
```
[Event "Casual Bullet game"]
[Site "https://lichess.org/BN43No8n"]
[Date "2022.03.20"]
[Round "?"]
[White "CenturyGaming"]
[Black "AttackingOrDefending"]
[Result "0-1"]
[Annotator "lichess.org"]
[BlackElo "2378"]
[BlackTitle "BOT"]
[ECO "D30"]
[Opening "Queen's Gambit Declined"]
[Termination "Normal"]
[TimeControl "60+2"]
[UTCDate "2022.03.20"]
[UTCTime "16:12:44"]
[Variant "Standard"]
[WhiteElo "2061"]

1. d4 { [%clk 0:01:00] } 1... d5 { [%clk 0:01:00] } 2. c4 { [%clk 0:01:02] }
2... e6 { [%clk 0:01:01] D30 Queen's Gambit Declined } 3. cxd5
{ [%clk 0:01:03] } 3... exd5 { [%clk 0:01:03] } 4. Nc3 { [%clk 0:01:03] } 4...
Bf5 { [%clk 0:01:04] } 5. Nf3 { [%clk 0:01:05] } 5... c6 { [%clk 0:01:06] } 6.
Bf4 { [%clk 0:01:06] } 6... Nf6 { [%clk 0:01:07] } 7. e3 { [%clk 0:01:07] }
7... Nbd7 { [%clk 0:01:09] } 8. Bd3 { [%clk 0:01:09] } 8... Bxd3
{ [%clk 0:01:10] } 9. Qxd3 { [%clk 0:01:11] } 9... a5 { [%clk 0:01:11] } 10. h3
{ [%clk 0:01:12] } 10... Bb4 { [%clk 0:00:56] } ( 10... Bb4 11. a3 Be7 12. O-O
O-O 13. Qc2 Re8 14. Rfc1 Bf8 15. Qb3 Qb6 16. Qc2 h6 17. Rab1 Qa6 18. a4 Qb6 19.
Kh1 Re6 20. Ne1 c5 21. dxc5 Nxc5 22. Nd3 { [%eval -0.10,27] } ) 11. a3
{ [%clk 0:01:13] } 11... Be7 { [%clk 0:00:54] } ( 11... Be7 12. O-O O-O 13. Qc2
Re8 14. Rfc1 Bf8 15. Ne1 Ne4 16. Nd3 Nb6 17. a4 Bd6 18. Nxe4 dxe4 19. Qb3 exd3
20. Bxd6 Nxa4 21. Bf4 Nb6 22. Qxd3 h6 23. Qc2 Nd5 { [%eval -0.03,23] } ) 12.
O-O { [%clk 0:01:13] } 12... O-O { [%clk 0:00:55] } ( 12... Ne5 13. Bxe5 Nd7
```
Game error:
```
2022-03-20 18:14:31,258: Error writing game record: AssertionError('san() and lan() expect move to be legal or null, but got f8e8 in r2qk2r/1p1nbppp/2p5/p2p4/3P1B2/P1NQPN1P/1P3PP1/R4RK1 b kq - 2 14')
```
Logs:
```
2022-03-20 18:12:39,952: --- Process Used. Total Queued: 0. Total Used: 1
2022-03-20 18:12:41,850: +++ https://lichess.org/BN43No8n/black Bullet vs CenturyGaming(2061)
2022-03-20 18:12:44,926:
2022-03-20 18:12:44,926: move: 1
2022-03-20 18:12:46,670: Got move d7d5 from chessdb.cn (depth: 50, score: 0)
2022-03-20 18:12:46,744: *** https://lichess.org/BN43No8n/black [player] AttackingOrDefending: b"Hi! I'm AttackingOrDefending. Good luck! Type !help for a list of commands I can respond to."
2022-03-20 18:12:46,835:
2022-03-20 18:12:46,836: move: 2
2022-03-20 18:12:47,284: Got move e7e6 from chessdb.cn (depth: 50, score: 0)
2022-03-20 18:12:47,999:
2022-03-20 18:12:48,000: move: 3
2022-03-20 18:12:48,478: Got move e6d5 from chessdb.cn (depth: 50, score: 0)
2022-03-20 18:12:51,109:
2022-03-20 18:12:51,110: move: 4
2022-03-20 18:12:51,560: Got move c8f5 from chessdb.cn (depth: 20, score: 0)
2022-03-20 18:12:51,970:
2022-03-20 18:12:51,970: move: 5
2022-03-20 18:12:52,493: Got move c7c6 from chessdb.cn (depth: 50, score: 0)
2022-03-20 18:12:53,256:
2022-03-20 18:12:53,258: move: 6
2022-03-20 18:12:53,701: Got move g8f6 from chessdb.cn (depth: 41, score: 0)
2022-03-20 18:12:54,632:
2022-03-20 18:12:54,633: move: 7
2022-03-20 18:12:55,117: Got move b8d7 from chessdb.cn (depth: 26, score: 0)
2022-03-20 18:12:55,626:
2022-03-20 18:12:55,627: move: 8
2022-03-20 18:12:56,194: Got move f5d3 from lichess cloud analysis (depth: 25, score: -7, knodes: 1871)
2022-03-20 18:12:56,409:
2022-03-20 18:12:56,410: move: 9
2022-03-20 18:12:57,013: Got move a7a5 from lichess cloud analysis (depth: 25, score: 2, knodes: 149379)
2022-03-20 18:12:58,197:
2022-03-20 18:12:58,198: move: 10
2022-03-20 18:12:58,762: Searching for wtime 71880 btime 68825
2022-03-20 18:13:15,169: depth: 27
2022-03-20 18:13:15,173: nps: 304578
2022-03-20 18:13:15,174: nodes: 4990513
2022-03-20 18:13:15,175: score: PovScore(Cp(+10), BLACK)
2022-03-20 18:13:15,176: ponderpv: 10...Bb4 11. a3 Be7 12. O-O O-O 13. Qc2 Re8 14. Rfc1 Bf8 15. Qb3 Qb6 16. Qc2 h6 17. Rab1 Qa6 18. a4 Qb6 19. Kh1 Re6 20. Ne1 c5 21. dxc5 Nxc5 22. Nd3
2022-03-20 18:13:16,723:
2022-03-20 18:13:16,724: move: 11
2022-03-20 18:13:17,250: Searching for wtime 72650 btime 53627
2022-03-20 18:13:20,746: depth: 23
2022-03-20 18:13:20,746: nps: 271488
2022-03-20 18:13:20,747: nodes: 945322
2022-03-20 18:13:20,747: score: PovScore(Cp(+3), BLACK)
2022-03-20 18:13:20,748: ponderpv: 11...Be7 12. O-O O-O 13. Qc2 Re8 14. Rfc1 Bf8 15. Ne1 Ne4 16. Nd3 Nb6 17. a4 Bd6 18. Nxe4 dxe4 19. Qb3 exd3 20. Bxd6 Nxa4 21. Bf4 Nb6 22. Qxd3 h6 23. Qc2 Nd5
2022-03-20 18:13:22,286:
2022-03-20 18:13:22,287: move: 12
2022-03-20 18:13:22,758: Got move e8g8 from chessdb.cn (depth: 22, score: 0)
2022-03-20 18:13:23,717:
2022-03-20 18:13:23,718: move: 13
2022-03-20 18:13:24,267: Searching for wtime 74440 btime 52950
2022-03-20 18:13:26,937: depth: 22
2022-03-20 18:13:26,937: nps: 320406
2022-03-20 18:13:26,938: nodes: 851961
2022-03-20 18:13:26,939: score: PovScore(Cp(+13), BLACK)
2022-03-20 18:13:26,939: ponderpv: 13...Nxe5 14. Bxe5 Nd7 15. Bf4 Re8 16. Qc2 Bf8 17. Rfd1 h6 18. Qb3 Qb6 19. Qc2 Qa6 20. a4 Qb6 21. Ne2 Rac8 22. Rd3 Nf6
2022-03-20 18:13:27,629:
2022-03-20 18:13:27,630: move: 14
2022-03-20 18:13:28,204: Searching for wtime 76440 btime 51565
2022-03-20 18:13:30,472: depth: 19
2022-03-20 18:13:30,473: nps: 277646
2022-03-20 18:13:30,473: nodes: 627203
2022-03-20 18:13:30,474: score: PovScore(Cp(+23), BLACK)
2022-03-20 18:13:30,475: ponderpv: 14...Nd7 15. Bg3 Nb6 16. Rfe1 Qd7 17. Qc2 a4 18. Rad1 f5 19. f3 Rf6 20. Bh4 Re6 21. Bxe7 Rxe7 22. e4 fxe4 23. fxe4 dxe4 24. Rxe4
2022-03-20 18:13:32,076:
2022-03-20 18:13:32,077: move: 15
2022-03-20 18:13:32,568: Searching for wtime 76980 btime 50598
2022-03-20 18:13:40,680: depth: 22
2022-03-20 18:13:40,681: nps: 255865
2022-03-20 18:13:40,681: nodes: 2074045
2022-03-20 18:13:40,682: score: PovScore(Cp(+21), BLACK)
2022-03-20 18:13:40,682: ponderpv: 15...Nb6 16. Qc2 Re8 17. a4 Nc4 18. Ne2 Nd6 19. Bh2 Ne4 20. Nf4 Bb4 21. Nd3 h5 22. Qd1 h4 23. Nxb4 axb4 24. Qb3
2022-03-20 18:13:44,622:
2022-03-20 18:13:44,623: move: 16
2022-03-20 18:13:45,130: Searching for wtime 75180 btime 43902
2022-03-20 18:13:51,322: depth: 22
2022-03-20 18:13:51,322: nps: 276947
2022-03-20 18:13:51,323: nodes: 1711537
2022-03-20 18:13:51,324: score: PovScore(Cp(+20), BLACK)
2022-03-20 18:13:51,325: ponderpv: 16...Re8 17. Na4 Nd7 18. Nb2 h5 19. Rfc1 Nf6 20. Qd1 Ne4 21. Be5 g6 22. Nd3 Bd6 23. Qe1 Bxe5 24. dxe5 Qg5 25. b4 axb4 26. axb4 Rxa1
2022-03-20 18:14:02,887:
2022-03-20 18:14:02,888: move: 17
2022-03-20 18:14:03,602: Searching for wtime 65760 btime 38906
2022-03-20 18:14:05,155: depth: 21
2022-03-20 18:14:05,156: nps: 314947
2022-03-20 18:14:05,156: nodes: 487538
2022-03-20 18:14:05,157: score: PovScore(Cp(+20), BLACK)
2022-03-20 18:14:05,158: ponderpv: 17...Nc8 18. Na4 Bd6 19. Bxd6 Nxd6 20. Nc5 h5 21. Qd1 Qg5 22. Nd3 Qh4 23. Ne5 Re7 24. a4 Re6 25. Nf3 Qe7 26. Rab1 g6 27. Ne5 Rf6 28. Rc2
2022-03-20 18:14:07,408:
2022-03-20 18:14:07,408: move: 18
2022-03-20 18:14:07,885: Searching for wtime 65710 btime 38794
2022-03-20 18:14:10,040: depth: 21
2022-03-20 18:14:10,040: nps: 369316
2022-03-20 18:14:10,041: nodes: 794399
2022-03-20 18:14:10,042: score: PovScore(Cp(+200), BLACK)
2022-03-20 18:14:10,043: ponderpv: 18...Bxa3 19. Rc2 Nd6 20. Ra1 Bb4 21. Na2 Qe7 22. Qd1 Nb5 23. Nc1 Nc3 24. Qf1 Ne4 25. Bf4 h6 26. Qd1 Qe6 27. Nd3 Qg6
2022-03-20 18:14:13,193:
2022-03-20 18:14:13,194: move: 19
2022-03-20 18:14:13,737: Searching for wtime 64770 btime 37936
2022-03-20 18:14:21,892: depth: 23
2022-03-20 18:14:21,893: nps: 271982
2022-03-20 18:14:21,893: nodes: 2216927
2022-03-20 18:14:21,897: score: PovScore(Cp(+191), BLACK)
2022-03-20 18:14:21,898: ponderpv: 19...Nd6 20. Ra1 Bb4 21. Bf4 Qe7 22. Qd1 Ne4 23. Na2 Qe6 24. Nc1 Qg6 25. Nd3 Nc3 26. Qd2 Nb5 27. Qd1 h5 28. Rac1 Re7 29. Ra1 Nc3 30. Qd2 Ne4 31. Qd1 Ree8 32. Rcc1 f6 33. Bc7
2022-03-20 18:14:28,495:
2022-03-20 18:14:28,496: move: 20
2022-03-20 18:14:29,008: Searching for wtime 60350 btime 31146
2022-03-20 18:14:30,522: depth: 15
2022-03-20 18:14:30,523: nps: 114633
2022-03-20 18:14:30,523: nodes: 172523
2022-03-20 18:14:30,523: score: PovScore(Cp(+243), BLACK)
2022-03-20 18:14:30,524: ponderpv: 20...Bb4 21. Bxd6 Bxd6 22. Na4 Bc7 23. g3 Ra7 24. Qd1 g6 25. Rba1 b6
2022-03-20 18:14:30,814: BOT AttackingOrDefending(2378?) won!
2022-03-20 18:14:30,814: CenturyGaming(2061) resigned.
2022-03-20 18:14:31,258: Error writing game record: AssertionError('san() and lan() expect move to be legal or null, but got f8e8 in r2qk2r/1p1nbppp/2p5/p2p4/3P1B2/P1NQPN1P/1P3PP1/R4RK1 b kq - 2 14')
2022-03-20 18:14:31,263: +++ Process Free. Total Queued: 0. Total Used: 0
2022-03-20 18:14:31,259: --- https://lichess.org/BN43No8n/black Game over
2022-03-20 18:15:20,483: Accept Bullet casual challenge from CenturyGaming(2061)
2022-03-20 18:15:20,775: --- Process Queue. Total Queued: 1. Total Used: 0
2022-03-20 18:15:20,865: --- Process Used. Total Queued: 0. Total Used: 1
2022-03-20 18:15:22,795: +++ https://lichess.org/wK1dLCf0/white Bullet vs CenturyGaming(2061)
2022-03-20 18:15:23,097:
2022-03-20 18:15:23,097: move: 1
2022-03-20 18:15:24,413: Got move a2a4 from chessdb.cn (depth: 45, score: 0)
2022-03-20 18:15:24,541: *** https://lichess.org/wK1dLCf0/white [player] AttackingOrDefending: b"Hi! I'm AttackingOrDefending. Good luck! Type !help for a list of commands I can respond to."
2022-03-20 18:15:26,477:
2022-03-20 18:15:26,478: move: 2
2022-03-20 18:15:26,927: Got move d2d4 from chessdb.cn (depth: 49, score: 0)
```

**Comment by MarkZH** [comment]
That was a subtle bug. It should be fixed now.

**Review by AttackingOrDefending — APPROVED** [review]

**Pull request merged**
