### PR TITLE
Define !wait command

### PR DESCRIPTION
**Pull request by SriMethan**

### CODE REVIEW

**Comment by SriMethan** [comment]
@MarkZH @attackingordefending

**Comment by SriMethan** [comment]
@MarkZH @AttackingOrDefending Are you merging this?

**Comment by MarkZH** [comment]
Thanks for the suggestion. I think a better description would be "(wait a minute for my first move)". This describes both what the command does and when it is applicable.

**Comment by SriMethan** [comment]
closing since the branch was deleted https://github.com/ShailChoksi/lichess-bot/pull/415

**Pull request closed without merging**
