### PR TITLE
Xboard engines can rejoin game after restarting lichess-bot.py

### PR DESCRIPTION
**Pull request by MarkZH**
If it is required that lichess-bot.py has to be shut down and restarted during a game, the following changes will allow for Xboard engines to rejoin the game in progress with access to the full game history for tracking 50-move draws and threefold repetitions.

This pull request starts from pull request #193, hence the similarity.

### CODE REVIEW

**Comment by MarkZH** [comment]
This should fix #199

**Review by ShailChoksi — APPROVED** [review]

**Comment by ShailChoksi** [comment]
@MarkZH Can you verify the merge conflict I just resolved

**Comment by MarkZH** [comment]
@ShailChoksi Everything works on my end.

**Comment by MarkZH** [comment]
@ShailChoksi The merge conflict resolution is good.

**Pull request merged**
