### PR TITLE
Allow XBoard bots of offer/accept draws and resign

### PR DESCRIPTION
**Pull request by MarkZH**
I'm submitting this PR as a draft since I'm not confident this works adequately yet. Critiques and comments are welcome.

These changes allow XBoard engines to resign games (by printing "resign" to stdout) and to offer/accept draws (by printing "offer draw" to stdout). There are no similar functions in UCI protocol.

Two problems so far:

1. The python-chess library will only pick up on "offer draw" if the bot prints it while thinking about a move. Otherwise, it is ignored. So, if the bot responds immediatlely to the "draw" command on line 262 before one of the choose_move functions can be called, it will be ignored.

2. When accepting a draw, the lichess API returns with

```
https://lichess.org:443 "POST /api/bot/game/za8D4j9z/move/c1f4?offeringDraw=1 HTTP/1.1" 400 43
Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/za8D4j9z/move/c1f4?offeringDraw=1)
```

The draw acceptance is properly accepted by lichess and the game actually ends with a draw. I'm not sure if the error message is
important.

### CODE REVIEW

**Comment by TheYoBots** [comment]
When would the bot offer/accept a draw and when would it resign? Would it be after determining the cp score and reaching an equal/drawish value (for offering/accepting draws) or is it something else?

**Comment by MarkZH** [comment]
It is completely up to the bot to make those decisions based on whatever criteria has been built in to them. Lichess-bot only passes along the messages.

At the moment, the only requirement is that the bot must output "offer draw" or "resign" while it is thinking about a move. Otherwise, lichess-bot will miss it.

**Comment by MarkZH** [comment]
I reported [the second issue](https://github.com/lichess-org/api/issues/108) and it was closed with [this commit](https://github.com/ornicar/lila/commit/d154719f0586d5e78df8c1c4e4244c1634c04793). I'll test this later.

**Comment by MarkZH** [comment]
For the first issue, there is a [feature request](https://github.com/niklasf/python-chess/issues/781) and a [pull request](https://github.com/niklasf/python-chess/pull/783). This means that other changes will be necessary to the code. Plus, this pull request will not be ready until the next release of python-chess.

**Comment by MarkZH** [comment]
With the latest version of python-chess released, this PR is now functional. Testing and comments are welcome.

**Comment by MarkZH** [comment]
Side note: Xboard engines now have more capabilities while using lichess-bot (offering draws and resigning) than UCI engines.

**Review by icecream17 — CHANGES_REQUESTED** [review]
Suggested changes in `strategies.py`

The `draw_offered` param needs to be added to `search_with_ponder` and `search` in `MinimalEngine`. (Although I currently have a pr to remove `search_with_ponder`)

**Review by ShailChoksi — APPROVED** [review]

**Comment by MarkZH** [comment]
There are bugs that require the following PRs to fix:

- #385 The example homemade bots return the right type for moves
- #391 There will be an error on the first move since lichess does not send the `bdraw` and `wdraw` fields to indicate a draw offer.

**Pull request merged**
