### PR TITLE
Cleanup installation instructions

### PR DESCRIPTION
**Pull request by MarkZH**
Mac/Linux:
- Add notes for non-Ubuntu distros
- Remove duplicate comment in virtualenv code

Windows:
- Remove link to video of Windows installation.
- Default Python installation is fine (one-user installation, default install directory, only need to add to PATH)
- Any windows command prompt works (cmd, PowerShell, Terminal) since `.bat` or `.ps1` is chosen automatically.
- Change example repo directory to discourage putting user files in `C:\`.
- Change virtualenv directory to `venv` to match Linux/Mac instructions.

### CODE REVIEW

**Comment by MarkZH** [comment]
The simpler windows instructions seem to work fine on my computer with cmd and Terminal.

**Comment by MarkZH** [comment]
At the moment, these instruction only seem to work for Python 3.10 and above.

**Comment by MarkZH** [comment]
I think I've corrected the instructions for Windows. It could use some testing by others.

**Comment by AttackingOrDefending** [comment]
Testing on windows 10 and python 3.8 `venv/Scripts/activate` didn't work. I had to use `venv\Scripts\activate`.

**Review by AttackingOrDefending — APPROVED** [review]

**Pull request merged**
