### PR TITLE
Ensure proper termination of sub-processes before attempting to restart

### PR DESCRIPTION
**Pull request by noobpwnftw**

### CODE REVIEW

**Comment by noobpwnftw** [comment]
There were three problems that should be fixed now:
1. Timeout on streams is needed or they can take a long time if not forever to fail with my Internet
2. `play_game` can get stuck in backoff with `board` is uninitialized while leaving the function
3. When control stream fails but not game stream or in a different order, it can cause races to resume active games

**Comment by noobpwnftw** [comment]
Additional exception catching for `check_online_status` and `get_ongoing_games`. Also stop engine pondering in case a book move is found, it makes no sense as next time it'll be another position to begin search with.

**Comment by MarkZH** [comment]
@noobpwnftw Do you have an idea of how much more work remains for this PR will be done? The latest change seems to be expanding the scope of this PR beyond ensuring that game processes are properly terminated in the event of errors. The handling of the matchmaking challenge ID looks like a good change, but I think it belongs in a new PR.

**Comment by noobpwnftw** [comment]
I hope the end is near. Hangs are not easily reproducible, so usually I wake up and fix the last thing shown in the logs.

**Comment by MarkZH** [comment]
OK. If the changes are relevant to the hangs, then that's fine. It's not fun debugging when the bugs can take days to show up.

**Comment by AttackingOrDefending** [comment]
Does this fix #607?

**Comment by noobpwnftw** [comment]
It should.

**Review by AttackingOrDefending — APPROVED** [review]

**Comment by AttackingOrDefending** [comment]
Is there any reason why `multiprocessing.set_start_method('spawn')` isn't run on tests?

**Comment by noobpwnftw** [comment]
Tests don't call `__main__`, which is required https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method

Platform defaults here:
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_start_method

**Review by MarkZH — APPROVED** [review]

**Pull request merged**
