### PR TITLE
Refactor recent challenge limit

### PR DESCRIPTION
**Pull request by MarkZH**
This is a refactoring that incorporates recent code changes into PR #593 and moves code to more appropriate functions and methods. Namely,

1. Update configuration parameter access
2. Move the checking for too many recent challenges into `Challenge.is_supported()`
3. Reduce the complexity of `Challenge.is_supported()`

### CODE REVIEW

**Comment by MarkZH** [comment]
I'm not sure how attribution works on github in PRs with multiple contributors, so merge #593 before merging this one. I want to make sure @bec-ca gets credit for their work.

**Comment by AttackingOrDefending** [comment]
I tested merging this PR [here](https://github.com/AttackingOrDefending/lichess-bot/tree/test) and got 3 authors (MarkZH, bec-ca, and myself). I assume I was credited as an author because I created the PR, so that shouldn't be a problem here. Also, TheYoBots did something similar in #424 and the attributions were correct.

I can't merge #593 because it has merge conflicts. I can resolve them myself, but then I will be credited as an author, so I would suggest merging only this PR.

**Comment by MarkZH** [comment]
OK. Just merge this one after you review it.

**Comment by AttackingOrDefending** [comment]
This PR has a few differences with #593, so I don't know if you want this to be merged.

**Comment by MarkZH** [comment]
I'll fix this up later.

**Comment by MarkZH** [comment]
This is ready for review.

**Review by AttackingOrDefending — APPROVED** [review]

**Pull request merged**
