### PR TITLE
When logging to a file, keep logging to console

### PR DESCRIPTION
**Pull request by MarkZH**
If the user opts to record lichess-bot logs to a file (-l), the program will keep printing messages to the console. Before, lichess-bot could only log to the console or to a file, but not both.

### CODE REVIEW

**Comment by MarkZH** [comment]
This definitely needs checking with Linux to make sure repeated messages don't start showing up.

As it is now, the log file records at the same verbosity as the console output. Should the text log always be verbose?

**Comment by AttackingOrDefending** [comment]
It doesn't work on my Linux VM. It doesn't print the engine stats (eval, depth, etc.) and the engine communication.
Before (file with -v -l):
old
After:
Terminal with -v -l:
vt
File with -v -l:
vf
Terminal with -l:
it
File with -l:
if

**Comment by MarkZH** [comment]
OK. Let's try something similar to what worked before.

**Comment by MarkZH** [comment]
Note to self: always run pytest before pushing.

**Comment by AttackingOrDefending** [comment]
It works now. Is it ready to be merged?
Terminal:
nfv
Logs:
nfv2

**Comment by MarkZH** [comment]
Yes, this is ready to merge.

**Review by AttackingOrDefending — APPROVED** [review]

**Pull request merged**
